# Database

POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: password77
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: myrh

# SERVER

SERVER_PORT: 8080
ACTIVATE_PROFILE: test

#EMAIL
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <Your email>
EMAIL_PASSWORD: <Your password>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}