name: MYRH CI FOR TESTING CODE AND UNIT TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'  # Specify the distribution (e.g., adopt, adopt-openj9, openjdk)
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success

      - name: Build with Maven without testing for now we need container Test for our database in the future so we can run test
        run: mvn clean install
#        -DskipTests=true


      - name: Run tests
        run: mvn clean test -B

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-application
          path: target/